CREATE DATABASE Medical;
GO

USE Medical

CREATE TABLE tipoUsuario
(	IdTipoUsuario INT PRIMARY KEY IDENTITY
	,tituloTipoUsuario VARCHAR (200) UNIQUE NOT NULL);
GO

CREATE TABLE Usuario
(
	IdUsuario INT PRIMARY KEY IDENTITY
	,IdTipoUsuario INT FOREIGN KEY REFERENCES tipoUsuario(IdTipoUsuario)
	,email VARCHAR (150) UNIQUE NOT NULL
	,senha VARCHAR (100) NOT NULL
);
GO

CREATE TABLE Especialidade 
(
	idEspecialidade INT PRIMARY KEY IDENTITY
	,nomeEspecialidade VARCHAR (100) UNIQUE NOT NULL
);
GO

CREATE TABLE Clinica 
(
	IdClinica INT PRIMARY KEY IDENTITY
	,CNPJ CHAR (14) UNIQUE
	,Endereco VARCHAR (200) UNIQUE NOT NULL
	,nomeFantasia VARCHAR (100) UNIQUE NOT NULL 
	,razaoSocial VARCHAR (150) UNIQUE NOT NULL
);
GO

CREATE TABLE Medico
(
	
	idMedico INT PRIMARY KEY IDENTITY
	,idUsuario INT FOREIGN KEY REFERENCES Usuario(idUsuario)
	,idEspecialidade INT FOREIGN KEY REFERENCES especialidade(idEspecialidade)
	,idClinica INT FOREIGN KEY REFERENCES clinica(idClinica)
	,nomeMedico VARCHAR (100) NOT NULL
	,CRM VARCHAR (50) UNIQUE NOT NULL
);
GO

CREATE TABLE Paciente
(
	IdPaciente INT PRIMARY KEY IDENTITY
	,IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario)
	,dataNascimento DATE NOT NULL
	,nomePaciente VARCHAR (100) NOT NULL
	,RG CHAR (9) UNIQUE NOT NULL
	,CPF CHAR (11) UNIQUE NOT NULL
	,telefone VARCHAR (11)
	,endereco VARCHAR (100) UNIQUE NOT NULL
);
GO

CREATE TABLE Situacao 
(
	IdSituacao INT PRIMARY KEY IDENTITY
	,situacao VARCHAR (30) NOT NULL

);
GO

CREATE TABLE Consulta
(
	IdConsulta INT PRIMARY KEY IDENTITY
	,IdMedico INT FOREIGN KEY REFERENCES Medico(IdMedico)
	,IdPaciente INT FOREIGN KEY REFERENCES Paciente(IdPaciente)
	,idSituacao INT FOREIGN KEY REFERENCES Situacao(idSituacao)
	,dataConsulta DATE NOT NULL
	,descricao VARCHAR (255) NOT NULL
)
